--
-- Create Schema Script 
--   Database Version   : 11.2.0.1.0 
--   Toad Version       : 10.1.1.8 
--   DB Connect String  : ORCL 
--   Schema             : POS 
--   Script Created by  : POS 
--   Script Created at  : 16/08/2020 11:59:40 AM 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 1         Columns: 1          
--   Sequences: 3 
--   Tables: 11         Columns: 99         Constraints: 2      


CREATE SEQUENCE POS_DETAILS_SEQUENCE
  START WITH 1020
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE POS_SEQUENCE
  START WITH 1120
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_PURCHASE
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE CUSTOMERS
(
  CUSTOMER_ID  NUMBER,
  NAME         VARCHAR2(100 BYTE),
  MODIFIED     TIMESTAMP(6),
  CREATED      TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ITEMS
(
  ITEM_ID           NUMBER,
  CODE              VARCHAR2(60 BYTE),
  NAME              VARCHAR2(100 BYTE),
  PACK_UNIT_ID      NUMBER,
  PACK_SIZE         NUMBER(8),
  STANDARD_UNIT_ID  NUMBER,
  CREATED           TIMESTAMP(6),
  MODIFIED          TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ITEM_PRICES
(
  ITEM_PRICE_ID   NUMBER,
  ITEM_ID         NUMBER,
  SALE_PRICE      NUMBER,
  EFFECTIVE_FROM  DATE,
  EFFECTIVE_TO    DATE,
  STATUS          NUMBER(1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE POS
(
  POS_ID            NUMBER,
  CUSTOMER          VARCHAR2(120 BYTE),
  CONTACT_NUMBER    VARCHAR2(20 BYTE),
  TOTAL             NUMBER,
  OTHER             NUMBER,
  PAYBLE            NUMBER,
  REMARKS           VARCHAR2(1200 BYTE),
  TRANSACTION_TYPE  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE POS_DETAILS
(
  POS_ID        NUMBER,
  CODE          VARCHAR2(60 BYTE),
  PRODUCT_NAME  VARCHAR2(120 BYTE),
  UOM           VARCHAR2(20 BYTE),
  QUANTITY      NUMBER,
  PRICE         NUMBER,
  AMOUNT        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PRODUCTS
(
  PRODUCT_ID           NUMBER(6),
  LANGUAGE_ID          VARCHAR2(3 BYTE),
  PRODUCT_NAME         NVARCHAR2(125),
  CATEGORY_ID          NUMBER(2),
  PRODUCT_DESCRIPTION  NVARCHAR2(2000),
  WEIGHT_CLASS         NUMBER(1),
  WARRANTY_PERIOD      INTERVAL YEAR(2) TO MONTH,
  SUPPLIER_ID          NUMBER(6),
  PRODUCT_STATUS       VARCHAR2(20 BYTE),
  LIST_PRICE           NUMBER(8,2),
  MIN_PRICE            NUMBER(8,2),
  CATALOG_URL          VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PURCHASES
(
  PURCHASE_ID  NUMBER(15)                       NOT NULL,
  USERNAME     VARCHAR2(40 BYTE),
  CANCEL       CHAR(1 BYTE),
  CREATED_ON   TIMESTAMP(6),
  MODIFIED_ON  TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PURCHASE_DETAILS
(
  PURCHASE_DETAIL_ID  NUMBER(15),
  PURCHASE_ID         NUMBER(15),
  CODE                VARCHAR2(40 BYTE),
  PRODUCT             VARCHAR2(40 BYTE),
  UOM                 VARCHAR2(20 BYTE),
  QUANTITY            NUMBER(15,2),
  PRICE               NUMBER(15,2),
  AMOUNT              NUMBER(15,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE RTEST
(
  A  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TEMP_ITEMS
(
  ITEMID           INTEGER,
  CANCEL           CHAR(1 BYTE),
  SOURCEID         INTEGER,
  MAPNAME          VARCHAR2(20 BYTE),
  USERNAME         VARCHAR2(50 BYTE),
  MODIFIEDON       DATE,
  CREATEDBY        VARCHAR2(50 BYTE),
  CREATEDON        DATE,
  WKID             VARCHAR2(15 BYTE),
  APP_DESC         NUMBER(1),
  ITEMNAME         VARCHAR2(200 BYTE),
  STDUNIT          NUMBER(16),
  PACKUNIT         NUMBER(16),
  BRANDCODE        VARCHAR2(10 BYTE),
  WHOLESALEPRICE   NUMBER(15,2),
  RETAILSALEPRICE  NUMBER(15,2),
  APP_LEVEL        NUMBER(3),
  APP_SLEVEL       NUMBER(3),
  CANCELREMARKS    VARCHAR2(150 BYTE),
  WFROLES          VARCHAR2(250 BYTE),
  PACKSIZE         NUMBER(6,2),
  PARTNO_TEMP      VARCHAR2(100 BYTE),
  ICAT             VARCHAR2(100 BYTE),
  TVAEXEMPT        VARCHAR2(10 BYTE),
  DISCCAT          VARCHAR2(100 BYTE),
  DISCCATID        NUMBER(15),
  SENDTOSITE       VARCHAR2(100 BYTE),
  SENDTRANSID      VARCHAR2(10 BYTE),
  ITEMCODE         VARCHAR2(50 BYTE),
  ITEMGROUP        NUMBER(16),
  MGROUP           NUMBER(16),
  MGROUPTEMP       NUMBER(15),
  TEMP_ITEMID      NUMBER(15),
  ITEMNAMETEMP     VARCHAR2(200 BYTE),
  PACKSIZE_OLD     NUMBER(6,2),
  CODE             VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE UOMS
(
  UOM_ID    NUMBER,
  NAME      VARCHAR2(60 BYTE),
  CREATED   TIMESTAMP(6),
  MODIFIED  TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE PURCHASES ADD (
  PRIMARY KEY
 (PURCHASE_ID));

ALTER TABLE PURCHASE_DETAILS ADD (
  FOREIGN KEY (PURCHASE_ID) 
 REFERENCES PURCHASES (PURCHASE_ID));